# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vermont Artisinal Internet
email: theproduct@justinburrows.com
description: > # this means to ignore newlines until "baseurl:"
 The Analog Digital Experience for Small to Medium Sized Businesses in Vermont.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.artisanalinternet.com" # the base hostname & protocol for your site
twitter_username: productjustin
github_username:  tmbdeclan

# Build settings
markdown: kramdown
